comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
wrap_comments = true
