[package]
name = "sqllogictest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
itertools = "0.10"
thiserror = "1"
log = "0.4"
