//! Resolve all expressions referring with their names.

use crate::catalog::*;
use crate::parser::{Ident, ObjectName, Statement};
use std::vec::Vec;

mod expression;
mod statement;

pub use self::expression::*;
pub use self::statement::*;

/// A bound SQL statement generated by the [`Binder`].
#[derive(Debug, PartialEq, Clone)]
pub enum BoundStatement {
    CreateTable(BoundCreateTable),
    Insert(BoundInsert),
}

/// The error type of bind operations.
#[derive(thiserror::Error, Debug, PartialEq)]
pub enum BindError {
    #[error("table must have at least one column")]
    EmptyColumns,
    #[error("database not found: {0}")]
    DatabaseNotFound(String),
    #[error("schema not found: {0}")]
    SchemaNotFound(String),
    #[error("table not found: {0}")]
    TableNotFound(String),
    #[error("column not found: {0}")]
    ColumnNotFound(String),
    #[error("duplicated table: {0}")]
    DuplicatedTable(String),
    #[error("duplicated column: {0}")]
    DuplicatedColumn(String),
    #[error("invalid table name: {0:?}")]
    InvalidTableName(Vec<Ident>),
    #[error("not nullable column: {0}")]
    NotNullableColumn(String),
    #[error("tuple length mismatch: expected {expected} but got {actual}")]
    TupleLengthMismatch { expected: usize, actual: usize },
    #[error("value should not be null in column: {0}")]
    NullValueInColumn(String),
}

/// The binder resolves all expressions referring to schema objects such as
/// tables or views with their column names and types.
pub struct Binder {
    catalog: RootCatalogRef,
}

impl Binder {
    /// Create a new [Binder].
    pub fn new(catalog: RootCatalogRef) -> Self {
        Binder { catalog }
    }

    /// Bind a statement.
    pub fn bind(&mut self, stmt: &Statement) -> Result<BoundStatement, BindError> {
        match stmt {
            Statement::CreateTable { .. } => {
                Ok(BoundStatement::CreateTable(self.bind_create_table(stmt)?))
            }
            Statement::Insert { .. } => Ok(BoundStatement::Insert(self.bind_insert(stmt)?)),
            _ => todo!("bind statement: {:#?}", stmt),
        }
    }
}

/// Split an [ObjectName] into `(database name, schema name, table name)`.
fn split_name(name: &ObjectName) -> Result<(&str, &str, &str), BindError> {
    Ok(match name.0.as_slice() {
        [table] => (DEFAULT_DATABASE_NAME, DEFAULT_SCHEMA_NAME, &table.value),
        [schema, table] => (DEFAULT_DATABASE_NAME, &schema.value, &table.value),
        [db, schema, table] => (&db.value, &schema.value, &table.value),
        _ => return Err(BindError::InvalidTableName(name.0.clone())),
    })
}
